# $schema: http://schema.asemicanalytics.com/v1/semantic_layer/event_logical_table.json
table_name: julia_raw.battle_ended
tags: [registration_event, activity_event]
columns:
  user_id:
    data_type: INTEGER
    tags: [entity_id_column]
  time:
    data_type: DATETIME
    tags: [event_timestamp_column]
  battle_duration: {data_type: INTEGER}
  elo_rating: {data_type: INTEGER}
  xp: {data_type: INTEGER}
  level: {data_type: INTEGER}
  arena_level: {data_type: INTEGER}
  battle: {data_type: INTEGER}
  tutorial_battle: {data_type: INTEGER}
  battle_type: {data_type: STRING}
  opponent_elo: {data_type: INTEGER}
  opponent_level: {data_type: INTEGER}
  opponent_arena_level: {data_type: INTEGER}
  won: {data_type: INTEGER}
  elo_reward: {data_type: INTEGER}
  session_id: {data_type: STRING}
  context_group_id: {data_type: STRING}
  log_counter: {data_type: INTEGER}
  _date:
    data_type: DATE
    tags: [date_column]
enrichments: []
