# $schema: http://schema.asemicanalytics.com/v1/semantic_layer/event_logical_table.json
table_name: julia_raw.currency_change
tags: [registration_event, activity_event]
columns:
  user_id:
    data_type: INTEGER
    tags: [entity_id_column]
  registration_day: {data_type: DATE}
  time:
    data_type: DATETIME
    tags: [event_timestamp_column]
  amount: {data_type: NUMBER}
  stash: {data_type: NUMBER}
  total_gained: {data_type: NUMBER}
  total_spent: {data_type: NUMBER}
  reason: {data_type: STRING}
  currency_type: {data_type: STRING}
  session_id: {data_type: STRING}
  context_group_id: {data_type: STRING}
  log_counter: {data_type: INTEGER}
  _date:
    data_type: DATE
    tags: [date_column]
enrichments: []
