# $schema: http://schema.asemicanalytics.com/v1/semantic_layer/action_logical_table.json
table_name: gendemo.ua_registration
tags: [first_appearance_action]
columns:
  user_id:
    data_type: INTEGER
    tags: [entity_id_column]
  time:
    data_type: DATETIME
    tags: [action_timestamp_column]
  session_id: {data_type: STRING}
  engagement: {data_type: NUMBER}
  payment_propensity: {data_type: NUMBER}
  skill: {data_type: NUMBER}
  platform:
    data_type: STRING
    tags: [first_appearance_property]
  application_version:
    data_type: INTEGER
    tags: [first_appearance_property]
  build_version:
    data_type: STRING
    tags: [first_appearance_property]
  country:
    data_type: STRING
    tags: [first_appearance_property]
  language: {data_type: STRING}
  manufacturer: {data_type: STRING}
  model: {data_type: STRING}
  os_version:
    data_type: STRING
    tags: [first_appearance_property]
  memory_size: {data_type: STRING}
  screen_width: {data_type: INTEGER}
  screen_height: {data_type: INTEGER}
  screen_dpi: {data_type: INTEGER}
  device_language: {data_type: INTEGER}
  date:
    data_type: DATE
    tags: [date_column]
enrichments: []
