table_name: "gendemo.ua_login"
tags:
  - activity_action

columns:
  - id: user_id
    data_type: INTEGER
    tags:
      - entity_id_column

  - id: time
    data_type: DATETIME
    tags:
      - action_timestamp_column

  - id: date
    data_type: DATE
    can_filter: false
    tags:
      - date_column

  - id: session_id
    data_type: STRING
    tags:
      - user_entity.session_id_column

  - id: platform
    data_type: STRING
    can_group_by: true
    tags:
      - user_entity.platform_column

  - id: country
    data_type: STRING
    can_group_by: true
    tags:
      - user_entity.platform_column

  - id: build_version
    data_type: STRING
    can_group_by: true
    tags:
      - generate_last_value_property


