# $schema: http://schema.asemicanalytics.com/v1/semantic_layer/action_logical_table.json
---
table_name: gendemo.ua_level_played
columns:
 -
  id: user_id
  data_type: INTEGER
  tags:
   - entity_id_column
 -
  id: skill
  data_type: NUMBER
 -
  id: time
  data_type: DATETIME
  tags:
   - action_timestamp_column
 -
  id: session_id
  data_type: STRING
 -
  id: level
  data_type: INTEGER
 -
  id: passed
  data_type: INTEGER
 -
  id: date
  data_type: DATE
  tags:
   - date_column
computed_columns: []
enrichments: []
