# $schema: http://schema.asemicanalytics.com/v1/semantic_layer/action_logical_table.json
table_name: gendemo.ua_purchase
tags: [payment_transaction_action]
columns:
  user_id:
    data_type: INTEGER
    tags: [entity_id_column]
  time:
    data_type: DATETIME
    tags: [action_timestamp_column]
  session_id: {data_type: STRING}
  platform: {data_type: STRING}
  country: {data_type: STRING}
  revenue:
    data_type: NUMBER
    tags: [transaction_amount_column]
  date:
    data_type: DATE
    tags: [date_column]
enrichments: []
