# $schema: http://schema.asemicanalytics.com/v1/semantic_layer/entity_kpis.json
kpis:
  active_users:
    select: SUM({property.cohort_size})
    where: '{property.days_since_last_active} <= 90'
    x_axis:
      date: {}
      cohort_day: {}
  dau:
    label: DAU
    select: SUM({property.active_on_day})
    x_axis:
      date: {total_function: avg}
      cohort_day: {}
  mau:
    label: MAU
    select: SUM({property.active_last_28_days})
    x_axis:
      date: {total_function: avg}
      cohort_day: {}
  mau_lost:
    label: MAU Lost
    select: SUM({property.cohort_size})
    where: '{property.days_since_last_active} = 27'
    x_axis:
      date: {}
      cohort_day: {}
  mdau:
    label: mDAU
    select: '{kpi.dau}'
    where: '{property.payers_lifetime} > 0'
    x_axis:
      date: {total_function: avg}
      cohort_day: {}
  retention:
    select: SAFE_DIVIDE({kpi.dau} * 100, SUM({property.cohort_size}))
    unit: {symbol: '%', is_prefix: false}
    x_axis:
      cohort_day: {}
  retention_d{}:
    select: SAFE_DIVIDE({kpi.dau} * 100, SUM({property.cohort_size}))
    where: '{property.cohort_day} = {}'
    unit: {symbol: '%', is_prefix: false}
    x_axis:
      date: {total_function: avg}
    template: cohort_day
  stickiness:
    select: SAFE_DIVIDE({kpi.dau} * 100, {kpi.mau})
    unit: {symbol: '%', is_prefix: false}
    x_axis:
      date: {}
