category: Engagement
kpis:
  - id: dau
    label: DAU
    x_axis:
     - date
    recommended: true
    sql:
      dau:
        select: "SAFE_DIVIDE(SUM({dau}), COUNT(DISTINCT {date}))"
    total: AVG

  - id: dau
    x_axis:
     - cohort_day
    recommended: true
    sql:
      dau:
        select: "SUM({dau})"

  - id: mdau
    label: mDAU
    x_axis:
     - date
    recommended: true
    sql:
      mdau:
        select: "SAFE_DIVIDE(SUM({dau}), COUNT(DISTINCT {date}))"
        where: "{is_payer}"
    total: AVG
  - id: mdau
    x_axis:
     - cohort_day
    sql:
      mdau:
        select: "SUM({dau})"
        where: "{is_payer}"

  - id: mau
    label: MAU
    x_axis:
     - date
    recommended: true
    sql:
      mau:
        select: "SAFE_DIVIDE(SUM({mau}), COUNT(DISTINCT {date}))"
    total: AVG
  - id: mau
    x_axis:
     - cohort_day
    recommended: true
    sql:
      mau:
        select: "SUM({mau})"

  - id: mau_lost
    label: MAU Lost
    sql:
      mau_lost:
        select: "SUM(if({date} - {last_login_date} = interval 29 day, 1, 0))"
    x_axis:
      - date
      - cohort_day

  - id: stickiness
    formula: 'SAFE_DIVIDE({dau} * 100, {mau})'
    unit: { symbol: "%", is_prefix: false }
    x_axis:
      - date
      - cohort_day

  - id: retention
    recommended: true
    formula: 'SAFE_DIVIDE({dau} * 100, {cohort_size})'
    unit: { symbol: "%", is_prefix: false }
    x_axis:
      - cohort_day

cohorted_daily_kpis_days: [1, 2, 3, 4, 5, 6, 7, 14, 28, 30, 60, 90, 180, 365]
cohorted_daily_kpis:
  - id: retention_d{}
    formula: 'SAFE_DIVIDE({dau} * 100, {cohort_size})'
    unit: { symbol: "%", is_prefix: false }
    sql:
      dau:
        select: "SUM({dau})"
        where: "{cohort_day} = {}"
      cohort_size:
        select: "SUM({cohort_size})"
        where: "{cohort_day} = {}"

