category: Engagement
kpis:
  - id: cohort_size
    sql:
      cohort_size:
        select: "SUM({cohort_size})"
    x_axis:
      - date
      - cohort_day

  - id: registrations
    sql:
      registrations:
        select: "SUM({cohort_size})"
        where: "{cohort_day} = 0"
    x_axis:
      - date
      - cohort_day
