# $schema: http://schema.asemicanalytics.com/v1/semantic_layer/entity_kpis.json
category: Registrations
kpis:
- id: registrations
  select: SUM({property.cohort_size})
  where: '{property.cohort_day} = 0'
  x_axis: [date, cohort_day]
