# $schema: http://schema.asemicanalytics.com/v1/semantic_layer/entity_kpis.json
kpis:
  arpdau:
    label: ARPDAU
    select: SAFE_DIVIDE({kpi.revenue}, {kpi.dau})
    unit: {symbol: $, is_prefix: true}
    x_axis:
      date: {}
      cohort_day: {}
  arppu:
    label: ARPPU
    select: SAFE_DIVIDE({kpi.revenue}, {kpi.daily_payers})
    unit: {symbol: $, is_prefix: true}
    x_axis:
      date: {}
      cohort_day: {}
  daily_payers:
    select: SUM({property.daily_payers})
    x_axis:
      date: {}
      cohort_day: {}
  ltv:
    label: LTV
    select: SAFE_DIVIDE(SUM({property.total_revenue}), SUM({property.cohort_size}))
    unit: {symbol: '%', is_prefix: false}
    x_axis:
      cohort_day: {}
  ltv_d{}:
    label: LTV D{}
    select: SAFE_DIVIDE(SUM({property.total_revenue}) * 100, SUM({property.cohort_size}))
    where: '{property.cohort_day} = {}'
    unit: {symbol: $, is_prefix: true}
    x_axis:
      date: {}
    template: cohort_day
  revenue:
    select: SUM({property.revenue})
    unit: {symbol: $, is_prefix: true}
    x_axis:
      date: {}
      cohort_day: {}
