# $schema: http://schema.asemicanalytics.com/v1/semantic_layer/entity_kpis.json
kpis:
  arpdau:
    label: ARPDAU
    select: SAFE_DIVIDE({kpi.revenue}, {kpi.dau})
    unit: {symbol: $, is_prefix: true}
    x_axis:
      date: {}
      cohort_day: {}
  arppu:
    label: ARPPU
    select: SAFE_DIVIDE({kpi.revenue}, {kpi.daily_payers})
    unit: {symbol: $, is_prefix: true}
    x_axis:
      date: {}
      cohort_day: {}
  daily_payers:
    select: SUM({property.payers_on_day})
    x_axis:
      date: {}
      cohort_day: {}
  ltv:
    label: LTV
    select: SAFE_DIVIDE({kpi.revenue} * 100, SUM({property.cohort_size}))
    unit: {symbol: '%', is_prefix: false}
    x_axis:
      cohort_day: {}
  ltv_d{}:
    label: LTV D{}
    select: SAFE_DIVIDE({kpi.revenue} * 100, SUM({property.cohort_size}))
    where: '{property.cohort_day} = {}'
    unit: {symbol: $, is_prefix: true}
    x_axis:
      date: {}
    template: cohort_day
  revenue:
    select: SUM({property.revenue_on_day})
    unit: {symbol: $, is_prefix: true}
    x_axis:
      date: {}
      cohort_day: {}
  revenue_last_2_days:
    select: SUM({property.revenue_last_2_days})
    unit: { symbol: $, is_prefix: true }
    x_axis:
      date: { }
      cohort_day: { }
  revenue_last_7_days_except_current_day:
    select: SUM({property.revenue_last_7_days_except_current_day})
    unit: { symbol: $, is_prefix: true }
    x_axis:
      date: { }
      cohort_day: { }
  revenue_day_before:
    select: SUM({property.revenue_day_before})
    unit: { symbol: $, is_prefix: true }
    x_axis:
      date: { }
      cohort_day: { }
