# $schema: http://schema.asemicanalytics.com/v1/semantic_layer/entity_kpis.json
kpis:
  active_users:
    select: SUM({property.cohort_size})
    where: '{property.days_since_last_active} <= 90'
    x_axis:
      _date: {}
      cohort_day: {}
  dau:
    label: DAU
    select: SUM({property.dau_active})
    x_axis:
      _date: {total_function: avg}
      cohort_day: {}
  wau:
    label: WAU
    select: SUM({property.wau_active})
    x_axis:
      _date: {total_function: avg}
      cohort_day: {}
  mau:
    label: MAU
    select: SUM({property.mau_active})
    x_axis:
      _date: {total_function: avg}
      cohort_day: {}
  mau_lost:
    label: MAU Lost
    select: SUM({property.mau_lost})
    x_axis:
      _date: {}
      cohort_day: {}
  mau_reactivated:
    label: MAU Reactivated
    select: SUM({property.mau_reactivated})
    x_axis:
      _date: {}
      cohort_day: {}
  retention:
    select: SAFE_DIVIDE({kpi.dau} * 100, SUM({property.cohort_size}))
    unit: {symbol: '%', is_prefix: false}
    x_axis:
      cohort_day: {}
  retention_d1:
    select: SAFE_DIVIDE({kpi.dau} * 100, SUM({property.cohort_size}))
    where: '{property.cohort_day} = 1'
    unit: {symbol: '%', is_prefix: false}
    x_axis:
      _date: {}
  retention_d7:
    select: SAFE_DIVIDE({kpi.dau} * 100, SUM({property.cohort_size}))
    where: '{property.cohort_day} = 7'
    unit: {symbol: '%', is_prefix: false}
    x_axis:
      _date: {}
  retention_d30:
    select: SAFE_DIVIDE({kpi.dau} * 100, SUM({property.cohort_size}))
    where: '{property.cohort_day} = 30'
    unit: {symbol: '%', is_prefix: false}
    x_axis:
      _date: {}
  retention_d90:
    select: SAFE_DIVIDE({kpi.dau} * 100, SUM({property.cohort_size}))
    where: '{property.cohort_day} = 90'
    unit: {symbol: '%', is_prefix: false}
    x_axis:
      _date: {}
  retention_d180:
    select: SAFE_DIVIDE({kpi.dau} * 100, SUM({property.cohort_size}))
    where: '{property.cohort_day} = 180'
    unit: {symbol: '%', is_prefix: false}
    x_axis:
      _date: {}
  stickiness:
    select: SAFE_DIVIDE({kpi.dau} * 100, {kpi.mau})
    unit: {symbol: '%', is_prefix: false}
    x_axis:
      _date: {}
