registration_columns: []

user_action_columns:
  - column:
      data_type: INTEGER
      id: dau
      label: DAU
    user_action_datasource: login
    aggregation_expression: "1"
    missing_value: 0

  - column:
      data_type: INTEGER
      id: dau_yesterday
      label: DAU yesterday
    user_action_datasource: login
    aggregation_expression: "1"
    missing_value: 0
    window: [-1, -1]

  - column:
      data_type: INTEGER
      id: mau
      label: MAU
    user_action_datasource: login
    aggregation_expression: "1"
    missing_value: 0
    window: [-29, 0]
    window_aggregation: sum

  - column:
      data_type: STRING
      id: _login_country
      can_filter: false
      can_group_by: false
    user_action_datasource: login
    aggregation_expression: "MAX({country})"
    can_materialize: false

total_columns:
  - column:
      data_type: STRING
      id: last_login_country
      can_group_by: true
    source_column: _login_country
    merge_expression: "COALESCE({__current}, {__total})"

computed_columns: []




