registration_columns:
  - column:
      data_type: STRING
      can_group_by: true
      id: registration_country
    source_column: country

  - column:
      data_type: STRING
      can_group_by: true
      id: registration_platform
    source_column: platform

user_action_columns: []
total_columns: []

computed_columns:
  - column:
      data_type: DATE
      can_group_by: true
      id: registration_week
    formula: "DATE_TRUNC({registration_date}, WEEK(MONDAY))"

  - column:
      data_type: DATE
      can_group_by: true
      id: registration_month
    formula: "DATE_TRUNC({registration_date}, MONTH)"

  - column:
      data_type: INTEGER
      can_group_by: true
      id: cohort_day
    formula: "DATE_DIFF({date}, {registration_date}, DAY)"




