category: Engagement
kpis:
  - id: dau
    label: DAU
    x_axis:
     - _date
    recommended: true
    sql:
      dau:
        select: "SAFE_DIVIDE(SUM({dau}), COUNT(DISTINCT {_date}))"
    total: AVG

  - id: dau
    x_axis:
     - cohort_day
    recommended: true
    sql:
      dau:
        select: "SUM({dau})"

  - id: mdau
    label: mDAU
    x_axis:
     - _date
    recommended: true
    sql:
      mdau:
        select: "SAFE_DIVIDE(SUM({dau}), COUNT(DISTINCT {_date}))"
        where: "{payer}"
    total: AVG
  - id: mdau
    x_axis:
     - cohort_day
    sql:
      mdau:
        select: "SUM({dau})"
        where: "{payer}"

  - id: wau
    label: WAU
    x_axis:
     - _date
    recommended: true
    sql:
      wau:
        select: "SAFE_DIVIDE(SUM({wau}), COUNT(DISTINCT {_date}))"
    total: AVG
  - id: wau
    x_axis:
     - cohort_day
    recommended: true
    sql:
      wau:
        select: "SUM({wau})"

  - id: mau
    label: MAU
    x_axis:
     - _date
    recommended: true
    sql:
      mau:
        select: "SAFE_DIVIDE(SUM({mau}), COUNT(DISTINCT {_date}))"
    total: AVG
  - id: mau
    x_axis:
     - cohort_day
    recommended: true
    sql:
      mau:
        select: "SUM({mau})"

  - id: mau_lost
    label: MAU Lost
    sql:
      mau_lost:
        select: "SUM(if({_date} - {last_logindate_} = interval 29 day, 1, 0))"
    x_axis:
      - _date
      - cohort_day
  #
  #  - id: mau_reactivated
  #    sql:
  #      mau_reactivated:
  #        select: "SUM(if({_date} - {previous_login_day} >= interval 29 day and {last_login_day} = {_date}, 1, 0))"
  #    x_axis:
  #      date_: { x: sum, y: sum }
  #      cohort_day: { x: sum, y: sum }

  - id: stickiness
    formula: 'SAFE_DIVIDE({dau} * 100, {mau})'
    unit: { symbol: "%", is_prefix: false }
    x_axis:
      - _date
      - cohort_day

  - id: retention
    recommended: true
    formula: 'SAFE_DIVIDE({dau} * 100, {cohort_size})'
    unit: { symbol: "%", is_prefix: false }
    x_axis:
      - cohort_day

  - id: avg_sessions
    formula: 'SAFE_DIVIDE({sessions_count}, {dau})'
    sql:
      sessions_count:
        select: "SUM({sessions_count})"

    x_axis:
      - _date
      - cohort_day

  - id: avg_session_length
    formula: 'SAFE_DIVIDE({playtime}, {sessions_count})'
    unit: { symbol: "min", is_prefix: false }
    sql:
      playtime:
        select: SUM({playtime})
      sessions_count:
        select: "SUM({sessions_count})"
    x_axis:
      - _date
      - cohort_day

  - id: avg_playtime
    formula: 'SAFE_DIVIDE({playtime}, {dau})'
    unit: { symbol: "min", is_prefix: false }
    sql:
      playtime:
        select: SUM({playtime})
    x_axis:
      - _date
      - cohort_day

cohorted_daily_kpis:
  - id: retention_d{}
    formula: 'SAFE_DIVIDE({dau} * 100, {cohort_size})'
    unit: { symbol: "%", is_prefix: false }
    sql:
      dau:
        select: "SUM({dau})"
        where: "{cohort_day} = {}"
      cohort_size:
        select: "SUM({cohort_size})"
        where: "{cohort_day} = {}"

