category: Revenue
kpis:
  - id: revenue
    label: IAP Revenue Gross USD
    recommended: true
    unit: { symbol: "$", is_prefix: true }
    sql:
      revenue:
        select: "SUM({revenue})"
    x_axis:
      - date
      - cohort_day

  #  - id: daily_purchase_rate
  #    formula: daily_payers * 100 / dau
  #    unit: { symbol: "%", is_prefix: false }
  #    x_axis:
  #      date_: { x: sum, y: sum }
  #      cohort_day: { x: sum, y: sum }
  #
  #  - id: daily_conversion
  #    formula: new_payers * 100 / dau
  #    unit: { symbol: "%", is_prefix: false }
  #    x_axis:
  #      date_: { x: sum, y: sum }
  #      cohort_day: { x: sum, y: sum }

  - id: arpdau_gross
    label: IAP ARPDAU Gross
    formula: 'SAFE_DIVIDE({revenue}, {dau})'
    recommended: true
    unit: { symbol: "$", is_prefix: true }
    x_axis:
      - date
      - cohort_day

  - id: arppu_gross
    label: IAP ARPPU Gross
    formula: 'SAFE_DIVIDE*({revenue}, {daily_payers})'
    recommended: true
    unit: { symbol: "$", is_prefix: true }
    x_axis:
      - date
      - cohort_day

  #  - id: avg_transaction_gross
  #    formula: gross_revenue_usd / transactions_count
  #    unit: { symbol: "$", is_prefix: true }
  #    sql:
  #      transactions_count:
  #        select: "SUM({transactions_count})"
  #    x_axis:
  #      date_: { x: sum, y: sum }
  #      cohort_day: { x: sum, y: sum }
  #
  #  - id: new_payers
  #    sql:
  #      select: "SUM({new_payers})"
  #    x_axis:
  #      date_: { x: sum, y: sum }
  #      cohort_day: { x: sum, y: sum }
  #
  - id: daily_payers
    sql:
      daily_payers:
        select: "SUM({daily_payers})"
    x_axis:
      - date
      - cohort_day
  #
  #  - id: total_payers
  #    sql:
  #      select: "SUM({total_payers})"
  #    x_axis:
  #      date_: { x: sum, y: sum }
  #      cohort_day: { x: sum, y: sum }

  - id: ltv
    label: LTV Gross
    formula: 'SAFE_DIVIDE({total_revenue}, {cohort_size})'
    unit: { symbol: "$", is_prefix: true }
    sql:
      total_revenue:
        select: "SUM({total_revenue})"
    x_axis:
      - cohort_day

cohorted_daily_kpis_days: [1, 2, 3, 4, 5, 6, 7, 14, 28, 30, 60, 90, 180, 365]
cohorted_daily_kpis:
  - id: ltv_gross_d{}
    formula: 'SAFE_DIVIDE({total_revenue}, {cohort_size})'
    unit: { symbol: "%", is_prefix: false }
    sql:
      total_revenue:
        select: "SUM({total_revenue})"
        where: "{cohort_day} = {}"
      cohort_size:
        select: "SUM({cohort_size})"
        where: "{cohort_day} = {}"

