# $schema: http://schema.asemicanalytics.com/v1/semantic_layer/entity_properties.json
properties:
  gold_gained:
    data_type: INTEGER
    can_filter: true
    can_group_by: false
    event_property: {source_event: currency_change, where: "{currency_type} = 'DemoData.Gold' and {amount} > 0", select: "{amount}", aggregate_function: sum, default_value: 0}
  gold_spent:
    data_type: INTEGER
    can_filter: true
    can_group_by: false
    event_property: {source_event: currency_change, where: "{currency_type} = 'DemoData.Gold' and {amount} < 0", select: "-{amount}", aggregate_function: sum, default_value: 0}
  gold_stash:
    data_type: INTEGER
    can_filter: true
    can_group_by: false
    event_property: {source_event: currency_change, where: "{currency_type} = 'DemoData.Gold'", select: "{stash}", aggregate_function: last_value, default_value: 0}
  gems_gained:
    data_type: INTEGER
    can_filter: true
    can_group_by: false
    event_property: {source_event: currency_change, where: "{currency_type} = 'DemoData.Gems' and {amount} > 0", select: "{amount}", aggregate_function: sum, default_value: 0}
  gems_spent:
    data_type: INTEGER
    can_filter: true
    can_group_by: false
    event_property: {source_event: currency_change, where: "{currency_type} = 'DemoData.Gems' and {amount} < 0", select: "-{amount}", aggregate_function: sum, default_value: 0}
  gems_stash:
    data_type: INTEGER
    can_filter: true
    can_group_by: false
    event_property: {source_event: currency_change, where: "{currency_type} = 'DemoData.Gems'", select: "{stash}", aggregate_function: last_value, default_value: 0}
