# $schema: http://schema.asemicanalytics.com/v1/semantic_layer/entity_properties.json
properties:
  battles_played:
    data_type: INTEGER
    can_filter: true
    can_group_by: true
    event_property: {source_event: battle_started, select: 1, aggregate_function: sum, default_value: 0}
  battles_won:
    data_type: INTEGER
    can_filter: true
    can_group_by: true
    event_property: {source_event: battle_ended, select: 1, aggregate_function: sum, default_value: 0}
  # arena_level:
  #   data_type: INTEGER
  #   can_filter: true
  #   can_group_by: true # TODO
  #   event_property: {source_event: battle_ended, select: 1, aggregate_function: last_value, default_value: 0}
  # elo_rating:
  battle_chests_opened:
    data_type: INTEGER
    can_filter: true
    can_group_by: true
    event_property: {source_event: open_chest, where: "{chest_type} = 'battle_chest'", select: 1, aggregate_function: sum, default_value: 0}
  silver_chests_opened:
    data_type: INTEGER
    can_filter: true
    can_group_by: true
    event_property: {source_event: open_chest, where: "{chest_name} = 'silver'", select: 1, aggregate_function: sum, default_value: 0}
  golden_chests_opened:
    data_type: INTEGER
    can_filter: true
    can_group_by: true
    event_property: {source_event: open_chest, where: "{chest_name} = 'golden'", select: 1, aggregate_function: sum, default_value: 0}
  magical_chests_opened:
    data_type: INTEGER
    can_filter: true
    can_group_by: true
    event_property: {source_event: open_chest, where: "{chest_name} = 'magical'", select: 1, aggregate_function: sum, default_value: 0}
  victory_chests_opened:
    data_type: INTEGER
    can_filter: true
    can_group_by: true
    event_property: {source_event: open_chest, where: "{chest_name} = 'victory_chest'", select: 1, aggregate_function: sum, default_value: 0}
  free_chests_opened:
    data_type: INTEGER
    can_filter: true
    can_group_by: true
    event_property: {source_event: open_chest, where: "{chest_name} = 'free_chest'", select: 1, aggregate_function: sum, default_value: 0}

