# $schema: http://schema.asemicanalytics.com/v1/semantic_layer/entity_properties.json
properties:
  active_on_day:
    data_type: INTEGER
    can_filter: false
    can_group_by: false
    action_property: {source_action: login, select: 1, aggregate_function: none, default_value: 0}
  was_active_on_day:
    data_type: STRING
    can_filter: true
    can_group_by: true
    computed_property:
      select: '{active_on_day}'
      value_mappings:
      - {constant: 0, new_value: Inactive on day}
      - {constant: 1, new_value: Active on day}
  days_active_last_7_days:
    data_type: INTEGER
    can_filter: true
    can_group_by: true
    sliding_window_property: {source_property: active_on_day, window_function: sum, relative_days_from: -6, relative_days_to: 0}
  days_active_last_28_days:
    data_type: INTEGER
    can_filter: true
    can_group_by: true
    sliding_window_property: {source_property: active_on_day, window_function: sum, relative_days_from: -27, relative_days_to: 0}
  active_last_28_days:
    data_type: INTEGER
    can_filter: false
    can_group_by: false
    sliding_window_property: {source_property: active_on_day, window_function: sum, relative_days_from: -27, relative_days_to: 0}
  days_since_last_active:
    data_type: INTEGER
    can_filter: true
    can_group_by: true
    computed_property: {select: 'DATE_DIFF({date}, {last_login_date}, DAY)'}
  last_login_date:
    data_type: DATE
    can_filter: true
    can_group_by: true
    lifetime_property:
      source_action_property: {source_action: login, select: '{date}', aggregate_function: last_value}
      merge_function: last_value
  last_login_platform:
    data_type: STRING
    can_filter: true
    can_group_by: true
    lifetime_property:
      source_action_property: {source_action: login, select: '{platform}', aggregate_function: last_value}
      merge_function: last_value
  last_login_application_version:
    data_type: INTEGER
    can_filter: true
    can_group_by: true
    lifetime_property:
      source_action_property: {source_action: login, select: '{application_version}', aggregate_function: last_value}
      merge_function: last_value
  last_login_build_version:
    data_type: STRING
    can_filter: true
    can_group_by: true
    lifetime_property:
      source_action_property: {source_action: login, select: '{build_version}', aggregate_function: last_value}
      merge_function: last_value
  last_login_country:
    data_type: STRING
    can_filter: true
    can_group_by: true
    lifetime_property:
      source_action_property: {source_action: login, select: '{country}', aggregate_function: last_value}
      merge_function: last_value
  last_login_os_version:
    data_type: STRING
    can_filter: true
    can_group_by: true
    lifetime_property:
      source_action_property: {source_action: login, select: '{os_version}', aggregate_function: last_value}
      merge_function: last_value
