# $schema: http://schema.asemicanalytics.com/v1/semantic_layer/event_logical_table.json
table_name: gendemo.event_table
tags: [registration_event, activity_event]
columns:
  user_id:
    data_type: INTEGER
    tags: [entity_id_column]
  date:
    data_type: DATE
    tags: [date_column]
  time:
    data_type: DATETIME
    tags: [event_timestamp_column]
  session_id: {data_type: STRING}
  event_name: {data_type: STRING}
  level_started.skill: {data_type: NUMBER}
  level_started.level: {data_type: INTEGER}
where: '{event_name} = ''level_started'''
enrichments: []
