# $schema: http://schema.asemicanalytics.com/v1/semantic_layer/entity_properties.json
properties:
  active_today:
    data_type: INTEGER
    can_filter: true
    can_group_by: true
    action_property: {source_action: activity, select: 1, aggregate_function: none, default_value: 0}
  active_1_day_ago:
    data_type: INTEGER
    can_filter: true
    can_group_by: true
    sliding_window_property: {source_action_property: active_today, sliding_window_function: sum, relative_days_from: -1, relative_days_to: -1}
  days_active_last_7_days:
    data_type: INTEGER
    can_filter: true
    can_group_by: true
    sliding_window_property: {source_action_property: active_today, sliding_window_function: sum, relative_days_from: -6, relative_days_to: 0}
  active_last_28_days:
    data_type: INTEGER
    can_filter: true
    can_group_by: true
    sliding_window_property: {source_action_property: active_today, sliding_window_function: max, relative_days_from: -27, relative_days_to: 0}
  last_login_date:
    data_type: DATE
    can_filter: true
    can_group_by: true
    lifetime_property:
      source_action_property: {source_action: activity, select: '{date}', aggregate_function: last_value}
      merge_function: last_value
  last_login_platform:
    data_type: STRING
    can_filter: true
    can_group_by: true
    lifetime_property:
      source_action_property: {source_action: activity, select: '{platform}', aggregate_function: last_value}
      merge_function: last_value
  last_login_application_version:
    data_type: INTEGER
    can_filter: true
    can_group_by: true
    lifetime_property:
      source_action_property: {source_action: activity, select: '{application_version}', aggregate_function: last_value}
      merge_function: last_value
  last_login_build_version:
    data_type: STRING
    can_filter: true
    can_group_by: true
    lifetime_property:
      source_action_property: {source_action: activity, select: '{build_version}', aggregate_function: last_value}
      merge_function: last_value
  last_login_country:
    data_type: STRING
    can_filter: true
    can_group_by: true
    lifetime_property:
      source_action_property: {source_action: activity, select: '{country}', aggregate_function: last_value}
      merge_function: last_value
  last_login_os_version:
    data_type: STRING
    can_filter: true
    can_group_by: true
    lifetime_property:
      source_action_property: {source_action: activity, select: '{os_version}', aggregate_function: last_value}
      merge_function: last_value
