# $schema: http://schema.asemicanalytics.com/v1/semantic_layer/entity_properties.json
properties:
  levels_played_count:
    data_type: NUMBER
    can_filter: true
    can_group_by: false
    action_property: {source_action: level_played, select: COUNT(*), aggregate_function: none, default_value: 0}

  max_level_played:
    data_type: INTEGER
    can_filter: true
    can_group_by: true
    action_property: { source_action: level_played, select: "{level_played.level}", aggregate_function: max, default_value: ~ }
