# $schema: http://schema.asemicanalytics.com/v1/semantic_layer/entity_properties.json
properties:
  first_appearance_date:
    data_type: DATE
    can_filter: true
    can_group_by: true
    first_appearance_property: {source_column: date}
  first_appearance_platform:
    data_type: STRING
    can_filter: true
    can_group_by: true
    first_appearance_property: {source_column: platform}
  first_appearance_application_version:
    data_type: INTEGER
    can_filter: true
    can_group_by: true
    first_appearance_property: {source_column: application_version}
  first_appearance_build_version:
    data_type: STRING
    can_filter: true
    can_group_by: true
    first_appearance_property: {source_column: build_version}
  first_appearance_country:
    data_type: STRING
    can_filter: true
    can_group_by: true
    first_appearance_property: {source_column: country}
  first_appearance_os_version:
    data_type: STRING
    can_filter: true
    can_group_by: true
    first_appearance_property: {source_column: os_version}
  cohort_day:
    data_type: INTEGER
    can_filter: true
    can_group_by: true
    computed_property:
      select: DATE_DIFF({date}, {first_appearance_date}, DAY)
      value_mappings: []
  cohort_size:
    data_type: INTEGER
    can_filter: false
    can_group_by: false
    computed_property:
      select: 1
      value_mappings: []
