# $schema: http://schema.asemicanalytics.com/v1/semantic_layer/entity_properties.json
first_appearance_properties:
- column:
    id: registration_date
    data_type: STRING
    can_filter: true
    can_group_by: true
  source_column: date
- column:
    id: registration_country
    data_type: STRING
    can_filter: true
    can_group_by: true
  source_column: country
- column:
    id: registration_platform
    data_type: STRING
    can_filter: true
    can_group_by: true
  source_column: platform
- column:
    id: registration_build_version
    data_type: STRING
    can_filter: true
    can_group_by: true
  source_column: build_version
action_properties: []
sliding_window_properties: []
total_properties: []
computed_properties:
- column:
    id: cohort_day
    data_type: INTEGER
    can_filter: true
    can_group_by: true
  formula: "{EPOCH_DAYS(date)} - {EPOCH_DAYS(registration_date)}"
- column:
    id: cohort_size
    data_type: INTEGER
    can_filter: true
    can_group_by: true
  formula: 1
