first_appearance_properties: []

action_properties:
  - column:
      data_type: NUMBER
      id: revenue
    action_datasource: purchase
    aggregation_expression: "SUM({revenue})"
    missing_value: 0

  - column:
      data_type: NUMBER
      id: revenue_28d
    action_datasource: purchase
    aggregation_expression: "SUM({revenue})"
    missing_value: 0
    window: [-27, 0]
    window_aggregation: sum

  - column:
      data_type: INTEGER
      id: daily_payers
    action_datasource: purchase
    aggregation_expression: "1"
    missing_value: 0

total_properties:
  - column:
      data_type: NUMBER
      id: total_revenue
    source_column: revenue
    merge_expression: "{__current} + COALESCE({__total}, 0)"

  - column:
      data_type: BOOLEAN
      can_group_by: true
      id: is_payer
    source_column: revenue
    merge_expression: "COALESCE({__total}, FALSE) OR ({__current} > 0)"

computed_properties: []




