# $schema: http://schema.asemicanalytics.com/v1/semantic_layer/entity_properties.json
properties:
  revenue:
    data_type: NUMBER
    can_filter: true
    can_group_by: true
    action_property: {source_action: payment_transaction, select: '{revenue}', aggregate_function: sum, default_value: 0}
  revenue_last_28_days:
    data_type: NUMBER
    can_filter: true
    can_group_by: true
    sliding_window_property: {source_action_property: revenue, sliding_window_function: sum, relative_days_from: -27, relative_days_to: 0}
  daily_payers:
    data_type: INTEGER
    can_filter: true
    can_group_by: false
    action_property: {source_action: payment_transaction, select: 1, aggregate_function: none, default_value: 0}
  transaction_count:
    data_type: NUMBER
    can_filter: true
    can_group_by: true
    action_property: {source_action: payment_transaction, select: COUNT(*), aggregate_function: none, default_value: 0}
  total_revenue:
    data_type: NUMBER
    can_filter: true
    can_group_by: true
    lifetime_property: {source_property: revenue, merge_function: sum}
  is_payer:
    data_type: BOOLEAN
    can_filter: true
    can_group_by: true
    lifetime_property: {source_property: is_daily_payer, merge_function: max}
  is_daily_payer:
    data_type: INTEGER
    can_filter: true
    can_group_by: true
    computed_property: {select: '{daily_payers} = 1'}
