table_name: "heroicmini_main.daily_user_history"
date_column: date_

columns:
  - id: _date
    data_type: DATE
    can_filter: false

  - id: gross_revenue_usd
    data_type: NUMBER

  - id: registration_country
    data_type: STRING
    can_group_by: true

  - id: registration_platform
    data_type: STRING
    can_group_by: true

computed_columns:
  - column:
      data_type: DATE
      can_group_by: true
      id: date_
    formula: "{_date}"

kpis:
  - id: gross_revenue_usd
    sql:
      gross_revenue_usd:
        select: "SUM({gross_revenue_usd})"

