table_name: "heroicmini_main.country_code"

columns:
  - id: country_code
    data_type: STRING
    can_group_by: true

  - id: country_name
    data_type: STRING
    can_group_by: true

computed_columns:
  - column:
      id: upper_case_country_name
      data_type: STRING
      can_group_by: true
    formula: "UPPER({country_name})"
