table_name: "gendemo.ua_purchase"
tags:
  - payment_transaction_datasource

columns:
  - id: user_id
    data_type: INTEGER
    tags:
      - user_id_column

  - id: time
    data_type: DATETIME
    tags:
      - timestamp_column

  - id: date
    data_type: DATE
    can_filter: false
    tags:
      - date_column

  - id: session_id
    data_type: STRING

  - id: platform
    data_type: STRING
    can_group_by: true

  - id: country
    data_type: STRING
    can_group_by: true

  - id: revenue
    data_type: NUMBER
    tags:
      - transaction_amount_column

kpis:
  - id: transaction_count
    sql:
      transaction_count:
        select: "COUNT(*)"

  - id: revenue
    sql:
      revenue:
        select: "SUM({revenue})"

