table_name: "gendemo.ua_level_started"
user_id_column: user_id
timestamp_column: time
date_column: date

columns:
  - id: user_id
    data_type: INTEGER

  - id: time
    data_type: DATETIME

  - id: date
    data_type: DATE
    can_filter: false

  - id: session_id
    data_type: STRING

  - id: level
    data_type: STRING
    can_group_by: true

kpis:
  - id: level_started_count
    sql:
      level_started_count:
        select: "COUNT(*)"

