table_name: "gendemo.ua_registration"
user_id_column: user_id
timestamp_column: time
date_column: date

columns:
  - id: user_id
    data_type: INTEGER

  - id: time
    data_type: DATETIME

  - id: date
    data_type: DATE
    can_filter: false

  - id: session_id
    data_type: STRING

  - id: platform
    data_type: STRING
    can_group_by: true

  - id: country
    data_type: STRING
    can_group_by: true

  - id: application_version
    data_type: STRING
    can_group_by: true

kpis:
  - id: registration_count
    sql:
      registration_count:
        select: "COUNT(*)"


