table_name: "gendemo.ua_login"
tags:
  - activity_datasource

columns:
  - id: user_id
    data_type: INTEGER
    tags:
      - user_id_column

  - id: time
    data_type: DATETIME
    tags:
      - timestamp_column

  - id: date
    data_type: DATE
    can_filter: false
    tags:
      - date_column

  - id: session_id
    data_type: STRING

  - id: platform
    data_type: STRING
    can_group_by: true
    tags:
      - platform_column

  - id: country
    data_type: STRING
    can_group_by: true
    tags:
      - country_column

  - id: build_version
    data_type: STRING
    can_group_by: true
    tags:
      - build_version_column

kpis:
  - id: login_count
    sql:
      login_count:
        select: "COUNT(*)"

