table_name: "gendemo.ua_purchase"
user_id_column: user_id
timestamp_column: time
date_column: date

columns:
  - id: user_id
    data_type: INTEGER

  - id: time
    data_type: DATETIME

  - id: date
    data_type: DATE
    can_filter: false

  - id: session_id
    data_type: STRING

  - id: platform
    data_type: STRING
    can_group_by: true

  - id: country
    data_type: STRING
    can_group_by: true

  - id: revenue
    data_type: NUMBER

kpis:
  - id: transaction_count
    sql:
      transaction_count:
        select: "COUNT(*)"

  - id: revenue
    sql:
      revenue:
        select: "SUM({revenue})"

