name: Backfill

on:
  workflow_dispatch:
    inputs:
      dateFrom:
        description: 'Backfill data from this date'
        required: true
      dateTo:
        description: 'Backfill data to this date'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Push
        run: |
          curl -L -o asemic-cli https://github.com/Bedrock-Data-Project/asemic-cli/releases/latest/download/asemic-cli-ubuntu
          chmod +x asemic-cli
          export ASEMIC_API_TOKEN=${{ secrets.ASEMIC_API_TOKEN }}
          export ASEMIC_APP_ID_DIR=config/heroicmini
          ./asemic-cli user-entity-model backfill --date-from=${{ github.event.inputs.dateFrom }} --date-to=${{ github.event.inputs.dateTo }}
