name: Validate

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download asemic-cli
        run: |
          curl -o asemic-cli https://github.com/Bedrock-Data-Project/asemic-cli/releases/download/latest/asemic-cli-ubuntu-latest
          chmod +x asemic-cli

      - name: Run the package
        working-directory: config/heroicmini
        run: |
          ASEMIC_API_TOKEN=${{ secrets.ASEMIC_TOKEN }} asemic-cli semantic-layer validate
