name: Validate

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install --index-url https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple asemic

      - name: Replace environment variables in file
        working-directory: heroicmini
        run: |
          sed -i "s/BQ_KEY/$SECRET/g" database.yml
        env:
          NEW_VARIABLE: ${{ secrets.BQ_KEY }}

      - name: Run the package
        working-directory: heroicmini
        run: |
          ASEMIC_TOKEN=${{ secrets.ASEMIC_TOKEN }} asemic validate
